---
elasticsearch_user: minotor
elasticsearch_password: fhoJWkJQhZvBCuzPazd345890LMwxNKJ
elasticsearch_hosts:  ["https://cerberus-alpha.ether-source.fr:9200", "https://cerberus-beta.ether-source.fr:9200", "https://cerberus-gamma.ether-source.fr:9200"]
log_level: INFO # CRITICAL => ERROR => WARNING => INFO => DEBUG
ca_path: ssl/chain.pem

api_adress: http://localhost
api_port: 8080            # run the api on the port given in api_port

coin_list:
  - "ethereum"
  - "the-open-network"
  - "zelcash"
  - "cosmos"
  - "osmosis"
  - "raptoreum"

flux_node_api_url: "https://runonflux.io/api/"
taddr: "13fCVN3cJ1Aqhi3CX5kR6oRpoR9UmzDMeo"
zelid: "L2NLpZCC1tTyRFoGoP2y6o47sgMLvPjCddrm5616UwPwkF11XZ5z"

token_watcher:
  - "cosmos"
  - "osmo"
  - "evmos"

url_token_watcher:
  - "https://cosmos.lcd.atomscan.com/"
  - "https://proxy.atomscan.com/osmo-lcd/"
  - "https://proxy.atomscan.com/evmos-lcd/"

grafana_api_token: glsa_S8RIBwaRs3WOxa4dLFSE5gK4k9Og67e3_e9a8091e
grafana_user: Minotor
grafana_password: RIBwaRs3WOxa4dLFSE5gK4k9Og67e3_e9a8091e
grafana_url: https://mermaid-alpha.ether-source.fr:3000

hopers_api: https://lcd-juno.keplr.app/cosmwasm/wasm/v1/contract/juno1u45shlp0q4gcckvsj06ss4xuvsu0z24a0d0vr9ce6r24pht4e5xq7q995n/smart/
hopers_custom: eyJiYWxhbmNlIjp7ImFkZHJlc3MiOiJqdW5vMTBuaHM1NTNhNWcydmU3bWg3MmplN2Y3emVlZzlhejdxbWZ0eWh3In19

